SevenTV/ServerGo

src/server/api/v2/websocket/helpers.go, src/server/api/v2/websocket/websocket.go
@AnatoleAM https://betterttv.com/emotes/5ff96aa5346b880825ab063d
=> Fix for subscriptions and graceful shutdown

docs/rest-api.md, src/mongo/datastructure/datastructure.go, src/mongo/mongo.go, src/server/api/v2/rest/badges/get-badges.go, src/server/api/v2/rest/rest.go, src/server/api/v2/rest/restutil/restutil.go, src/utils/web.go
This is the initial implementation of an endpoint to return active 7TV user badges.
Changes
* Creating the Badge struct type and database collection
* Adding a REST endpoint /v2/badges to return badge data
=> Badges Implementation

src/mongo/datastructure/emote.go, src/server/api/v2/rest/emotes/create-emote.go
Converting the raw shell command exec to [gographics/imagick](https://github.com/gographics/imagick)
=> Use `gographics/imagick` for webp emote conversion

src/server/api/v2/rest/emotes/create-emote.go
Reverting changes in #28 as it causes panic in production.
=> Revert compression changes

.github/workflows/deploy-stage.yaml, k8s/ingress/7tv-ingress.yaml, k8s/ingress/grafana-ingress.yaml, k8s/production.yaml, k8s/stage.yaml, src/redis/redis.go, src/server/api/v2/rest/emotes/create-emote.go
Merging the currently staged changes on emote compression into live
=> Emote Compression Upgrade

src/server/api/v2/gql/resolvers/query/query.go
Allowing query by Twitch ID on GQL "user" query
=> GQL - Allow querying Users by Twitch ID

src/mongo/datastructure/datastructure.go, src/mongo/datastructure/defaults.go, src/server/api/v2/gql/resolvers/errors.go, src/server/api/v2/gql/resolvers/mutation/mutation.go, src/server/api/v2/gql/resolvers/mutation/user-edit.go, src/server/api/v2/gql/scheme/scheme.gql
Adding a GQL command to mutate user data.
=> API/GQL - User Mutation

src/mongo/datastructure/datastructure.go, src/server/api/v2/gql/resolvers/mutation/user-edit.go, src/server/api/v2/gql/resolvers/query/query.go, src/server/api/v2/gql/scheme/scheme.gql
Adding the full list of available application-wide roles to the GQL meta query
=> API/GQL - Add Roles to meta query

src/server/api/v2/gql/resolvers/query/query.go, src/server/api/v2/gql/scheme/scheme.gql
Adding a new filter parameter to find emotes by minimum and maximum width
=> API/GQL (Search Emotes) - Width Range Filter

src/mongo/datastructure/datastructure.go, src/mongo/mongo.go, src/server/api/actions/actions.go, src/server/api/actions/emotes.go, src/server/api/actions/notifications.go, src/server/api/v2/gql/resolvers/mutation/emote-delete.go, src/server/api/v2/gql/resolvers/mutation/emote-edit.go, src/server/api/v2/gql/resolvers/mutation/notification.go, src/server/api/v2/gql/resolvers/query/notification.go, src/server/api/v2/gql/resolvers/query/user.go, src/server/api/v2/gql/scheme/scheme.gql, src/server/api/v2/rest/restutil/restutil.go, src/utils/utils.go
Implementing a complete notification system, creating a direct line of communication to end-users for alerts such as moderation actions or other messages relevant to a user or group of users.
=> Notification System

src/cache/cache.go, src/mongo/datastructure/datastructure.go, src/mongo/mongo.go, src/server/api/actions/actions.go, src/server/api/actions/emote-delete.go, src/server/api/actions/emote-merge.go, src/server/api/actions/emotes.go, src/server/api/actions/notifications.go, src/server/api/v2/gql/resolvers/mutation/emote-delete.go, src/server/api/v2/gql/resolvers/mutation/emote-edit.go, src/server/api/v2/gql/resolvers/mutation/emote-merge.go, src/server/api/v2/gql/scheme/scheme.gql, src/server/api/v2/rest/emotes/create-emote.go
Adding the Emote Merging functionality and a GQL Mutation command
=> Emote Merge

src/discord/webhooks.go, src/server/api/actions/emote-merge.go, src/server/api/v2/gql/resolvers/mutation/user-edit.go
=> Add More Notifications

src/server/api/v2/rest/emotes/get-emote.go
Adding an endpoint which takes an emote ID and converts the CDN image into a GIF for discord compatibility
=> API/REST - Endpoint to convert WEBP emotes to GIF

src/server/api/v2/gql/resolvers/query/emotes.go
Fixing the sorting and pagination with emote channels, which currently breaks after the first page
=> Fix Emote Channels Sorting & Pagination

src/mongo/datastructure/datastructure.go, src/server/api/v2/rest/emotes/get-global-emotes.go, src/server/api/v2/rest/restutil/restutil.go, src/server/api/v2/rest/users/get-channel-emotes.go
Some updates to rate limits and caching for the REST API
=> REST RateLimit & Cache Changes 

config.example.yaml, demo.yaml, go.mod, go.sum, main.go, src/configure/config.go, src/discord/discord.go, src/discord/webhooks.go, src/server/health/health.go, src/server/server.go
Logging various health reports within the app to a discord channel and properly checking for the availability of critical services. Returning a 503 on `/health` if a service is downed.
=> Health & Panic Alerts

src/server/api/v2/gql/resolvers/query/query.go
Undoes https://github.com/SevenTV/ServerGo/pull/35
=> Undoes the previous FFZ hotfix.

config.example.yaml
Also make sure to update production config!
=> Bump Chatterino7 version to v7.3.4

src/server/api/v2/chatterino/chattterino.go
someone must've force-pushed and danked up my fix from d8da9d4e51ae6a8a206226a8625568d38407ae09
=> Fix chatterino endpoints in the API

src/server/api/v2/rest/users/edit-profile-picture.go
Fixes the conversion from gif to webp for avatars
=> Avatar gif to webp fix

src/server/api/v2/rest/cosmetics/cosmetics.go
Changed the pipeline altogether, it now starts from the badges collection instead of entitlements. It's now a lot more complex and dank, but seems to be as efficient as it can possibly get.
This also fixes priority.
=> REST/Cosmetics - Further improvements
